export const AUTH_API_LOADING = '@AUTH/AUTH_API_LOADING';
export const AUTH_API_FAILED = '@AUTH/AUTH_API_FAILEd';
export const CHANGE_LOGIN_STATE = '@AUTH/CHANGE_LOGIN_STATE';
export const LOGIN_SUCCESS = '@AUTH/LOGIN_SUCCESS';